-- Initialize UI
local UI = loadstring(game:HttpGet("https://raw.githubusercontent.com/spxnso/ElementalUI/refs/heads/main/source.lua"))()

local Window = UI:New({
    DefaultTheme = "Dark",
    UITitle = "Elemental Hub"
})

-- Create a main tab
local MainTab = Window:Tab("Main")

-- Button example with an icon
local Button = MainTab:Button("🚀 Launch", function()
    print("Launching...")
end)

-- Slider example with an icon
local Slider = MainTab:Slider("🔊 Volume", 0, 100, function(value)
    print("Volume set to:", value)
end)

-- Toggle example with an icon
local Toggle = MainTab:Toggle("⚡ Enable Power Mode", false, function(state)
    print("Power mode:", state and "ON" or "OFF")
end)

-- Dropdown example with an icon
local Dropdown = MainTab:Dropdown("📜 Select Option", {"Option 1", "Option 2", "Option 3"}, function(selected)
    print("Selected:", selected)
end)

-- Textbox example with an icon
local Textbox = MainTab:Textbox("✍️ Enter text...", function(text)
    print("Textbox input:", text)
end)

-- Label example with an icon
local Label = MainTab:Label("ℹ️ This is a label")

-- Separator example with an icon
local Separator = MainTab:Separator("🔗 Section", "This is a separator")

-- Frame Display example with an icon
local Frame = MainTab:FrameDisplay("📦 Info Box", "This is a simple info box.")

-- This was generated by ChatGPT, I know. Was too lazy to write an example.
